config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :participants, only: %i(create update)
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/joinus' => 'visitors#joinus'

   root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :participants
  has_many :users, through: :participants
  belongs_to  :author, class_name: "User"

  validates :title, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :description, presence: true
  validates :place, presence: true
  validates :author_id, presence: true
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  extend Enumerize
  enumerize :participation, in: %i(going interested ignore), scope: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  extend Enumerize
  enumerize :auth, in: %i(admin normal)

  has_many :participants
  has_many :events, through: :participants

  validates :name, presence: true
  validates :employee_id, presence: true
  validates :auth, presence: true
  validates :entry_date, presence: true
  validates :retire_date, presence: true
  default_value_for :entry_date, Date.today
  default_value_for :retire_date, '9999-12-31'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :id_invalid
  before_action :authenticate_user!

  def id_invalid(e)
    render 'shared/record_not_found', status: 404
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    unless session[:user_id]
      redirect_to new_session_path
    end
  end

  def user_signed_in?
    !!current_user
  end

  helper_method :current_user
  helper_method :user_signed_in?
  
end

app/controllers/events_controller.rb
require 'time'

class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i(index show)
  before_action :set_event, only: %i(show edit update destroy)

  def new
    if params[:date].present?
      @event = Event.new(author: current_user,
                         start_time: params[:date].to_datetime,
                         end_time: params[:date].to_datetime)
    else
      @event = Event.new(author: current_user)
    end
  end

  def index
    # TODO: 返り値がないの気持ち悪い。
    event2json
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html {
          redirect_to @event,
          notice: 'event was successfully created.'
        }
        # format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new',
          notice: 'Information is not enough.'
        }
        # format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html {
          redirect_to @event,
          notice: 'event was successfully created!!'
        }
        #format.json {}
      else
        format.html { render 'new' }
        #format.json
      end
    end
  end

  def destroy
    @event.destroy

    respond_to do |format|
      format.html {
        redirect_to events_url ,
        notice: 'event was successfully deleted!!'
      }
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :start_time, :end_time,
                                  :description, :place, :author_id)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event2json
    gon.events = Event.all.map do |event|
      {
        "id": event.id,
        "title": event.title,
        "url": "https://hack-scheduler-shhr1214.c9users.io/events/#{event.id}",
        "class": "event-inverse",
        "start": event.start_time.to_s,
        "end": event.end_time.to_s,
      }
    end
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_event
  def create
    @event.participants.create!(user: current_user, participation: params[:commit])
    redirect_to event_path(@event), notice: "参加表明しました"
  end

  def update
    participant = @event.participants.find_by(user: current_user)
    participant.update!(participation: params[:commit])
    redirect_to event_path(@event), notice: "ステータスを更新しました"
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!
  helper_method :current_user

  def new
  end

  def create
    user = User.find_by_name params[:name]
    if user && user.authenticate(params[:pass])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:error] = "Invalid account."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery except: [:update]
  skip_before_action :authenticate_user!, only: %i(new create)
  before_action :set_user, only: %i(show edit update destroy)

  def new
    @user = User.new
    @user.auth = :normal
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created!!'
      #format.json {}
    else
      render 'new'
      #format.html
      #format.json
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully created!!' }
        #format.json {}
      else
        #format.html
        #format.json
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url , notice: 'User was successfully deleted!!' }
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :employee_id, :auth, :password, :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  skip_before_action :authenticate_user!
  def joinus
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => "form-horizontal" } do |f| %>

  <% if @event.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="row">
      <%= f.label :title, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="row">
      <%= f.label :start_time, :class => 'control-label col-lg-2' %>
      <div class="col-lg-3">
        <%= f.text_field :start_time, :class => 'form-control datetimepicker'%>
      </div>
      <%= f.label :end_time, :class => 'control-label col-lg-2' %>
      <div class="col-lg-3">
        <%= f.text_field :end_time, :class => 'form-control datetimepicker' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="row">
      <%= f.label :place, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :place, :class => 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="row">
      <%= f.label :description, :class => 'control-label col-lg-2' %>
      <div class="col-xs-10">
        <%= f.text_area :description, :class => 'form-control', :rows => "5" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-lg-10">
        <%= f.hidden_field :author_id, :class => 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn btn-default' %>
      </div>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $(function(){
      $('.datetimepicker').datetimepicker({
          format: 'YYYY-MM-DD HH:mm'
      });
  });
</script>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1>
    <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'],
                   :model => model_class.model_name.human.titleize %>
  </h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<div id="calendar"></div>

<script type="text/javascript">
  "use strict";

  $(document).ready(function() {
    // page is now ready, initialize the calendar...
    $('#calendar').fullCalendar({
      header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'
			},
			defaultView: 'month',
      events: gon.events,

      dayClick: function(date, jsEvent, view) {
        window.location.href = './events/new?date=' + date._d;
      }
        // put your options and callbacks here
    })
  });
</script>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1>
    <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'],
        :model => model_class.model_name.human.titleize %>
  </h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>

<div class="row">
  <div class='col-lg-9'>
    <div class="page-header">
      <h1><%= @event.title %></h1>
    </div>

    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:author_id) %>:</strong></dt>
      <dd><%= @event.author.name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:start_time) %>:</strong></dt>
      <dd><%= l @event.start_time %></dd>
      <dt><strong><%= model_class.human_attribute_name(:end_time) %>:</strong></dt>
      <dd><%= l @event.end_time %></dd>
      <dt><strong><%= model_class.human_attribute_name(:place) %>:</strong></dt>
      <dd><%= @event.place %></dd>
      <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
      <dd><%= @event.description %></dd>
    </dl>

      <dl class="dl-horizontal">
        <%= link_to t('.back', default: t("helpers.links.back")),
                      events_path, class: 'btn btn-default'  %>
        <% if user_signed_in? && (current_user == @event.author || current_user.auth == :admin) %>
          <%= link_to t('.edit', default: t("helpers.links.edit")),
                        edit_event_path(@event), class: 'btn btn-default' %>
          <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                        event_path(@event),
                        method: 'delete',
                        data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                        class: 'btn btn-danger' %>
        <% end %>
      </dl>
    </div>

  <div class="col-lg-3">
    <div class="well sidebar-nav">
      <% participant = @event.participants.find_or_initialize_by(user: current_user) %>
      <%= form_for [@event, participant] do |f| %>
      <h3>Participants List</h3>
      <ul class="nav nav-list">
        <p>
          <li><%= f.submit 'going', style: 'color: gray', class: 'btn btn-link' %></li>
          <ul>
            <% @event.participants.with_participation(:going).each do |participant| %>
              <li><%= participant.user.name %></li>
            <% end %>
          </ul>
        </p>
        <p>
          <li><%= f.submit 'interested', style: 'color: gray', class: 'btn btn-link' %></li>
          <ul>
            <% @event.participants.with_participation(:interested).each do |participant| %>
              <li><%= participant.user.name %></li>
            <% end %>
          </ul>
        </p>
        <p>
          <li><%= f.submit 'ignore', style: 'color: gray', class: "btn btn-link" %></li>
          <ul>
            <% @event.participants.with_participation(:ignore).each do |participant| %>
              <li><%= participant.user.name %></li>
            <% end %>
          </ul>
        </p>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HackScheduler" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <%= include_gon %>

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "HackScheduler", events_path, class: "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? && current_user.auth == :admin %>
              <li><%= link_to "Users", users_path  %></li>
            <% end %>
            <li>
              <% if current_user == nil %>
                <%= link_to "Login", new_session_path %>
              <% else %>
                <%= link_to "Logout", session_path(current_user.id), method: :delete, data: {confirm: 'ログアウトしますか？'} %>
              <% end %>
            </li>
          </ul>
          <%= link_to image_tag("logo.png",  class: 'logo'), joinus_path %>
        </div>
      </div>
    </div>

    <div class="container">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
            <button aria-hidden="true" class="close" data-dismiss="alert" type="button">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>

      <%= yield %>

      <footer>
        <p>&copy; Hackers' Club 2015</p>
      </footer>

    </div>

  </body>
</html>

app/views/shared/comming_soon.html.erb
<h1>This page is comming soon!</h1>

app/views/shared/record_not_found.html.erb
<h1>404 Not Found</h1>

app/views/users/_form.html.erb
<%= form_for @user, html: { class: "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %>
          prohibited this user from being saved:
        </h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="row">
      <%= f.label :name, class: 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <%= f.label :employee_id, class: 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :employee_id, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <%= f.label :password, class: 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <%= f.label :password_confirmation, class: 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>
  </div>
  <% if user_signed_in? && current_user.auth == "admin" %>
    <div class="form-group">
      <div class="row">
        <%= f.label :auth, class: 'control-label col-lg-2' %>
        <div class="col-lg-3">
          <%= f.select :auth, User.auth.options, {}, class: 'form-control' %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="row">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  users_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:employee_id) %></th>
      <th><%= model_class.human_attribute_name(:auth) %></th>
      <th><%= model_class.human_attribute_name(:entry_date) %></th>
      <th><%= model_class.human_attribute_name(:retire_date) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.employee_id %></td>
        <td><%= user.auth %></td>
        <td><%= user.entry_date %></td>
        <td><%= user.retire_date %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:employee_id) %>:</strong></dt>
  <dd><%= @user.employee_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @user.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:auth) %>:</strong></dt>
  <dd><%= @user.auth %></dd>
  <dt><strong><%= model_class.human_attribute_name(:entry_date) %>:</strong></dt>
  <dd><%= @user.entry_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:retire_date) %>:</strong></dt>
  <dd><%= @user.retire_date %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/visitors/joinus.html.erb
<h1>ハッカー部へようこそ</h1>
<p>
  <dl>
    <dt>活動期間</dt>
    <dd>平日朝７時〜８時４５分</dd>
    <dt>場所</dt>
    <dd>本社3階会議室（リモートでもOK）</dd>
  </dl>
</p>